### PR TITLE
KOGITO-1424 - Upgrade examples to Kogito 0.8.1

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Review by evacchi — APPROVED** [review]
looks good. I'd like someone [to take a look at using units](https://github.com/evacchi/kogito-travel-agency-tutorial/tree/master/01-kogito-travel-agency/src/main/resources/org/acme/travels/rules) or I'll do it somewhere around next week

**Review by evacchi — CHANGES_REQUESTED** [review]
make sure you change

```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-kogito</artifactId>
    </dependency>
```

to `org.kie.kogito:kogito-quarkus`

**Comment by cristianonicolai** [comment]
@evacchi fixed

**Review by evacchi — APPROVED** [review]
ping me when this is merged, I want to upgrade to rule units

**Review by ricardozanini — APPROVED** [review]

**Pull request merged**
